export const country = Object.freeze([

    { name: 'Albania' },
    { name: 'Azerbaijan' },
    { name: 'Andorra' },
    { name: 'Armenia' },
    { name: 'Austria' },
    { name: 'Belarus' },
    { name: 'Belgium' },
    { name: 'Bosnia Herzegovina' },
    { name: 'Bulgaria' },
    { name: 'Croatia' },
    { name: 'Czech' },
    { name: 'Cyprus' },
    { name: 'Denmark' },
    { name: 'Estonia' },
    { name: 'France' },
    { name: 'Finland' },
    { name: 'Georgia' },
    { name: 'Greece' },
    { name: 'Germany' },
    { name: 'Hungary' },
    { name: 'Iceland' },
    { name: 'Ireland' },
    { name: 'Italy' },
    { name: 'Kosovo' },
    { name: 'Latvia' },
    { name: 'Liechtenstein' },
    { name: 'Lithuania' },
    { name: 'Luxembourg' },
    { name: 'Moldova' },
    { name: 'Malta' },
    { name: 'Monaco' },
    { name: 'Montenegro' },
    { name: 'Macedonia' },
    { name: 'Netherlands' },
    { name: 'Norway' },
    { name: 'Poland' },
    { name: 'Portugal' },
    { name: 'Romania' },
    { name: 'Russia' },
    { name: 'San Marino' },
    { name: 'Slovakia' },
    { name: 'Serbia' },
    { name: 'Slovenia' },
    { name: 'Spain' },
    { name: 'Sweden' },
    { name: 'Switzerland' },
    { name: 'Turkey' },
    { name: ' Ukraine' },
    { name: 'United Kingdom' }
]);